# remote_theme: tuur29/pages-themes-cayman
theme: jekyll-theme-slate
title: HKUST-DNN_DA
description: State-level COVID-19 Trend Forecasting using Deep Neural Networks with Data Augmentation
show_downloads: false
# google_analytics: G-DDFGPDH5TE
github:
  is_project_page: false
updated_on: 2022-02-21
model_date: 2022-02-19
colors:
    gradient_left: "#d04b18"
    gradient_right: "#dfb24a"
