# remote_theme: tuur29/pages-themes-cayman
theme: jekyll-theme-cayman
title: HKUST-DNN-DA
description: State-level COVID-19 Trend Forecasting using Deep Neural Networks with Data Augmentation
show_downloads: false
# google_analytics: G-DDFGPDH5TE
github:
  is_project_page: false
updated_on: 2021-11-01
model_date: 2021-10-30
colors:
    gradient_left: "#d04b18"
    gradient_right: "#dfb24a"
theme: jekyll-theme-slate